### ISSUE TITLE
Validate JSON

### ISSUE THREAD

**Issue by lawlietlaw** [mathewOrtiz/MsspSentinel#10]
Need to add in a portion to validate JSON objects are being built correctly at run time. 

Additionally need to ensure all ARM templates have the necessary parameters already completed.

**Comment by mathewOrtiz** [comment]
ARM Template has been modified to be built using a hashtable initially for readable & support of adding in the necessary values. This is then dynamically placed into a JSON file which will allow for us to utilize the parameters without issue with the JSON templates.
