### ISSUE TITLE
Second Lighthouse deployment for CSP

### ISSUE THREAD

**Issue by lawlietlaw** [mathewOrtiz/MsspSentinel#21]
Need to add another lighthouse deployment & with this the PAL linking needs to be done as well. 

- [ ] Configures the arm template parameters for deployment
- [ ] Pulls down the ARM template
- [ ] PAL Linkage commands are able to be run successfully. 
- [ ] Validate that we can authenticate with our own user after the Second light house deployment. 
- [ ] Confirm All of the above is working correctly.

**Comment by mathewOrtiz** [comment]
Still working to determine the correct PAL linkages for the ARM template to leverage.

**Comment by mathewOrtiz** [comment]
This is still pending outstanding issues in creating the connection.

**Comment by mathewOrtiz** [comment]
This is being closed out as this issue isn't a responsibility of the SOC team.
